#!/bin/sh

#INFO: ejecutar un script como aplicacion web
EMRT_BIN=$( cd "$( dirname "$0" )" && pwd )
PORT=$1 ; shift
SCRIPT=$1 ; shift
~/opt/jdk17/bin/java -Dlibrt.webapp=$SCRIPT -DHttpsKeysDir=$EMRT_BIN/etc -DHttpsPort=$PORT '-Dfile.encoding=UTF-8' -jar $EMRT_BIN/jetty-runner-8.jar  --config $EMRT_BIN/etc/jetty8.xml --lib $EMRT_BIN $EMRT_BIN/emrt.jar
