SELECT AREANAME,CONSTR,ALIMEN,PELOS,BIDIREC,NODOS,FECHA_HAB,DOC,DISPO1,DISPO2,MANZANAS,VIVIENDAS,CLIENTES,ANCHO_BANDA,
NSE_NODO,PARTIDO,LABEL_MGT,VIV_RELEV,ORD_PORC,ZONA_COMERCIAL,ZONA_UST,SCHED_AREA,DESCRIPCION,CABLEMODEM,RXO,TECNICO_ID,
FECHA_ALTA_CABLEMODEM,GRILLA_REDUCIDA,FECHA_HAB_DIGITALIZADA,PLAN_DALVI,EMPRESA,RED,FECHA_HAB_UNIFICACION,AGRUP_SUBNODO,
MARCA_IN,CANAL_BARRIAL,PHONE,FECHA_HAB_PHONE,ESTADO,AGRUP_DIRECTA,FECHA_NORMAL_RED,TIPO_BIDIREC,FECHA_CAMBIO_BIDIREC,VOD,
FECHA_CAMBIO_AB,FECHA_HAB_VOD,FECHA_CAMBIO_BIDIREC_OLD,TIPO_BIDIREC_OLD,FECHA_HAB_PHONE_OLD,PHONE_OLD,
FECHA_HAB_DIGITALIZADA_OLD,GRILLA_REDUCIDA_OLD,FECHA_CAMBIO_AB_OLD,PELOS_OLD,ANCHO_BANDA_OLD,VOD_OLD,FECHA_HAB_VOD_OLD,
VIABLE_2W,TX_NODO,PUERTO_APEX,NODE_GROUP,OM_NODO,ANTIGUEDAD_RED,APEX,OM,MAX_VEL_ACC,FECHA_CAMBIO_VEL,MAX_VEL_ACC_OLD,
LOGIDFROM,LOGIDTO 
FROM GIS_DET_AREA_H
WHERE logIdTo = 0 
AND logIdFrom > $logIdSyncMin AND logIdFrom <= $logIdSyncMax